"""Metrics collection for speculative decoding experiments on Mac edge."""
import json
import time
from pathlib import Path
from typing import Dict, List, Any, Optional
from dataclasses import dataclass, asdict
from datetime import datetime
import numpy as np


@dataclass
class RequestMetrics:
    """Metrics collected per request."""
    request_id: str
    timestamp: str
    
    # Timing
    total_latency: float  # Total time from request start to completion
    edge_draft_time: float  # Time spent on edge drafting
    server_verify_time: float  # Time spent on server verification
    
    # Tokens
    generated_tokens: int  # Total tokens generated by server
    total_drafted_tokens: int  # Total tokens drafted by edge
    accepted_drafted_tokens: int  # Tokens accepted by server
    wasted_drafted_tokens: int  # Drafted - accepted
    
    # Speculative decoding specific
    k_chosen: int  # K value chosen for this request
    acceptance_ratio: float  # Accepted / drafted
    total_rounds: int  # Number of verification rounds
    
    # Network
    uplink_bytes: int  # Bytes sent to server
    downlink_bytes: int  # Bytes received from server
    rtt: float  # Round-trip time
    
    # Computed metrics
    tokens_per_sec: float  # Generated tokens / total latency
    tpot: float  # Time per output token (total latency / generated tokens)
    
    def to_dict(self) -> Dict[str, Any]:
        return asdict(self)


class MetricsCollector:
    """Collects and aggregates metrics for experiments."""
    
    def __init__(self, output_dir: Path = Path("results")):
        self.output_dir = output_dir
        self.output_dir.mkdir(exist_ok=True)
        
        self.request_metrics: List[RequestMetrics] = []
        self.start_time: Optional[float] = None
        self.current_request_id: Optional[str] = None
        
        # Request-level tracking
        self._request_start: Optional[float] = None
        self._draft_start: Optional[float] = None
        self._verify_start: Optional[float] = None
        self._network_start: Optional[float] = None
        
    def start_request(self, request_id: str) -> None:
        """Start tracking a new request."""
        self.current_request_id = request_id
        self._request_start = time.time()
        self.start_time = self.start_time or time.time()
    
    def start_draft(self) -> None:
        """Start edge draft timing."""
        self._draft_start = time.time()
    
    def end_draft(self) -> None:
        """End edge draft timing."""
        if self._draft_start:
            self._edge_draft_time = time.time() - self._draft_start
            self._draft_start = None
    
    def start_verify(self) -> None:
        """Start server verify timing."""
        self._verify_start = time.time()
    
    def end_verify(self) -> None:
        """End server verify timing."""
        if self._verify_start:
            self._server_verify_time = time.time() - self._verify_start
            self._verify_start = None
    
    def start_network(self) -> None:
        """Start network timing for RTT."""
        self._network_start = time.time()
    
    def end_network(self) -> None:
        """End network timing."""
        if self._network_start:
            self._rtt = time.time() - self._network_start
            self._network_start = None
    
    def record_request(
        self,
        generated_tokens: int,
        drafted_tokens: int,
        accepted_tokens: int,
        k_chosen: int,
        rounds: int,
        uplink_bytes: int = 0,
        downlink_bytes: int = 0,
    ) -> None:
        """Record completed request metrics."""
        if not self._request_start:
            raise RuntimeError("Request not started")
        
        total_latency = time.time() - self._request_start
        
        # Get accumulated timing
        edge_draft_time = getattr(self, '_edge_draft_time', 0.0)
        server_verify_time = getattr(self, '_server_verify_time', 0.0)
        rtt = getattr(self, '_rtt', 0.0)
        
        # Compute derived metrics
        wasted_tokens = drafted_tokens - accepted_tokens
        acceptance_ratio = accepted_tokens / drafted_tokens if drafted_tokens > 0 else 0.0
        tokens_per_sec = generated_tokens / total_latency if total_latency > 0 else 0.0
        tpot = total_latency / generated_tokens if generated_tokens > 0 else 0.0
        
        metrics = RequestMetrics(
            request_id=self.current_request_id,
            timestamp=datetime.now().isoformat(),
            total_latency=total_latency,
            edge_draft_time=edge_draft_time,
            server_verify_time=server_verify_time,
            generated_tokens=generated_tokens,
            total_drafted_tokens=drafted_tokens,
            accepted_drafted_tokens=accepted_tokens,
            wasted_drafted_tokens=wasted_tokens,
            k_chosen=k_chosen,
            acceptance_ratio=acceptance_ratio,
            total_rounds=rounds,
            uplink_bytes=uplink_bytes,
            downlink_bytes=downlink_bytes,
            rtt=rtt,
            tokens_per_sec=tokens_per_sec,
            tpot=tpot,
        )
        
        self.request_metrics.append(metrics)
        
        # Reset tracking
        self._request_start = None
        self._edge_draft_time = 0.0
        self._server_verify_time = 0.0
        self._rtt = 0.0
    
    def compute_aggregate_metrics(self) -> Dict[str, Any]:
        """Compute aggregate metrics across all requests."""
        if not self.request_metrics:
            return {}
        
        metrics_data = [m.to_dict() for m in self.request_metrics]
        
        # Latency metrics
        latencies = [m["total_latency"] for m in metrics_data]
        
        # TPOT metrics
        tpots = [m["tpot"] for m in metrics_data]
        
        # Tokens/sec metrics
        tps = [m["tokens_per_sec"] for m in metrics_data]
        
        # Acceptance ratio metrics
        acceptance_ratios = [m["acceptance_ratio"] for m in metrics_data]
        
        # Wasted tokens metrics
        wasted_tokens = [m["wasted_drafted_tokens"] for m in metrics_data]
        
        # K chosen metrics
        k_values = [m["k_chosen"] for m in metrics_data]
        
        # Network metrics
        rtts = [m["rtt"] for m in metrics_data]
        edge_draft_times = [m["edge_draft_time"] for m in metrics_data]
        server_verify_times = [m["server_verify_time"] for m in metrics_data]
        
        # Per-request totals
        total_generated_tokens = sum(m["generated_tokens"] for m in metrics_data)
        total_drafted_tokens = sum(m["total_drafted_tokens"] for m in metrics_data)
        total_accepted_tokens = sum(m["accepted_drafted_tokens"] for m in metrics_data)
        total_wasted_tokens = sum(m["wasted_drafted_tokens"] for m in metrics_data)
        total_uplink = sum(m["uplink_bytes"] for m in metrics_data)
        total_downlink = sum(m["downlink_bytes"] for m in metrics_data)
        
        return {
            "summary": {
                "total_requests": len(self.request_metrics),
                "total_duration_seconds": time.time() - self.start_time if self.start_time else 0,
            },
            "per_request_totals": {
                "total_latency": sum(latencies),
                "generated_tokens": total_generated_tokens,
                "tokens_per_sec": total_generated_tokens / sum(latencies) if sum(latencies) > 0 else 0,
                "tpot": sum(tpots) / len(tpots) if tpots else 0,
                "total_rounds": sum(m["total_rounds"] for m in metrics_data),
                "mean_k_chosen": sum(k_values) / len(k_values) if k_values else 0,
                "acceptance_ratio": total_accepted_tokens / total_drafted_tokens if total_drafted_tokens > 0 else 0,
                "total_drafted_tokens": total_drafted_tokens,
                "total_accepted_drafted_tokens": total_accepted_tokens,
                "total_wasted_drafted_tokens": total_wasted_tokens,
                "uplink_bytes": total_uplink,
                "downlink_bytes": total_downlink,
                "average_rtt": sum(rtts) / len(rtts) if rtts else 0,
                "average_server_verify_time": sum(server_verify_times) / len(server_verify_times) if server_verify_times else 0,
                "average_edge_draft_time": sum(edge_draft_times) / len(edge_draft_times) if edge_draft_times else 0,
            },
            "per_condition": {
                "mean_latency": np.mean(latencies),
                "p50_latency": np.percentile(latencies, 50),
                "p95_latency": np.percentile(latencies, 95),
                "mean_tpot": np.mean(tpots),
                "mean_tokens_per_sec": np.mean(tps),
                "mean_acceptance_ratio": np.mean(acceptance_ratios),
                "mean_wasted_drafted_tokens": np.mean(wasted_tokens),
                "variance_acceptance_ratio": np.var(acceptance_ratios),
            },
        }
    
    def save_metrics(self, condition_name: str) -> None:
        """Save metrics to files."""
        timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
        
        # Save per-request metrics
        request_file = self.output_dir / f"{condition_name}_requests_{timestamp}.json"
        with open(request_file, "w") as f:
            json.dump([m.to_dict() for m in self.request_metrics], f, indent=2)
        
        # Save aggregate metrics
        aggregate = self.compute_aggregate_metrics()
        aggregate_file = self.output_dir / f"{condition_name}_aggregate_{timestamp}.json"
        with open(aggregate_file, "w") as f:
            json.dump(aggregate, f, indent=2)
        
        print(f"✅ Saved metrics:")
        print(f"   Requests: {request_file}")
        print(f"   Aggregate: {aggregate_file}")
        
        # Print summary
        if aggregate:
            print(f"\n📊 Summary:")
            print(f"   Total requests: {aggregate['summary']['total_requests']}")
            print(f"   Mean latency: {aggregate['per_condition']['mean_latency']:.3f}s")
            print(f"   P50 latency: {aggregate['per_condition']['p50_latency']:.3f}s")
            print(f"   P95 latency: {aggregate['per_condition']['p95_latency']:.3f}s")
            print(f"   Mean tokens/sec: {aggregate['per_condition']['mean_tokens_per_sec']:.1f}")
            print(f"   Mean acceptance ratio: {aggregate['per_condition']['mean_acceptance_ratio']:.3f}")
            print(f"   Mean wasted tokens: {aggregate['per_condition']['mean_wasted_drafted_tokens']:.1f}")


# Convenience function for simple usage
def create_metrics_collector(output_dir: str = "results") -> MetricsCollector:
    """Create a new metrics collector."""
    return MetricsCollector(Path(output_dir))
